version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    command:
      ["sh", "-c", "mongod --bind_ip_all --auth --quiet > /dev/null 2>&1"]

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:1234@mongo:27017

  frontend:
    build:
      context: ./travelly_front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./travelly_front:/app
      - /app/node_modules # 컨테이너 내부 의존성 캐시
    stdin_open: true
    tty: true
    command: ["yarn", "dev", "--host"]
